name: Build documentation

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  documentation_build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: goanpeca/setup-miniconda@v1
      name:  Conda setup
      with:
        python-version: 3.7
        activate-environment: standard
        environment-file: devtools/envs/standard.yaml
        auto-activate-base: false

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install --no-deps -v .
        if [ -f docs/requirements.txt ]; then pip install -r docs/requirements.txt; fi
    - name: Build sphinx documentation
      run: |
        cd docs/
        make html
    # https://github.com/peaceiris/actions-gh-pages
    - name: Deploy documentation
      if: success()
      uses: peaceiris/actions-gh-pages@v3
      with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/html/
          user_name: 'Ana Sánchez'
          user_email: 'ana.sanchez01@estudiant.upf.edu'
